apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp
spec:
  selector: # Pod selector
    matchLabels:
      env: myapp
  replicas: 3 # Number of replicas
  template: # Pod template
    metadata:
      name: nginx-2
      labels:
        env: myapp
    spec:
      containers:
        - name: nginx
          image: nginx