apiVersion: v1
kind: Service
metadata:
  name: back-end
spec:
  type: ClusterIP
  ports:
    - targetPort: 80 # Port exposed by the container
      port: 80 # Port of the service
  selector: # Pod selector - link the service to the pods
    env: myapp
    type: back-end
